### ISSUE TITLE
not working!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [marco-almeida/spotifyToMp3#1]
my friend not working!please help me!

**Comment by marco-almeida** [comment]
what's not working?

**Comment by marco-almeida** [comment]
> my friend not working!please help me!

what's not working?

**Comment by KENPOKASMMA1982** [comment]
I MEAN NOT DOWNLOAD THE CORRECT MUSIC DUDE!!!

**Comment by marco-almeida** [comment]
> I MEAN NOT DOWNLOAD THE CORRECT MUSIC DUDE!!!

read description it do be like that sometimes
